### ISSUE TITLE
 unresolved import `rdll::SEXP`

### ISSUE THREAD

**Issue by elferdo** [rustr/rustinr#3]
Hi,

First of all, thanks for the great work! I've been loving Rcpp for some time and it's wonderful being able to use rust in R.

At least it would be, if I could. I can install _rustinr_ without a problem:

```
> devtools::install_github("rustr/rustinr")
 Downloading GitHub repo rustr/rustinr@master
 from URL https://api.github.com/repos/rustr/rustinr/zipball/master
 Installing rustinr
 '/usr/local/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
   --quiet CMD INSTALL  \
   '/tmp/RtmpRWPkdV/devtools596e3e72e27a/rustr-rustinr-6d4107f'  \
   --library='/usr/home/elferdo/R' --install-tests

 * installing *source* package ‘rustinr’ ...
 ** R
 ** inst
 ** tests
 ** preparing package for lazy loading
 ** help
 *** installing help indices
 ** building package indices
 ** testing if installed package can be loaded
 * DONE (rustinr)
 > library(rustinr)
```
Now when I enter the first example:

```
 rust('
 // #[rustr_export]                                                                                      
 pub fn say_hi() -> String{
     "Hello World".into()
 }
 ')

!> > + . + say_hi()
     Updating registry `https://github.com/rust-lang/crates.io-index`
  Downloading rustr v0.1.9
    Compiling rustr v0.1.9
 error[E0432]: unresolved import `rdll::SEXP`
  --> /home/elferdo/.cargo/registry/src/github.com-1ecc6299db9ec823/rustr-0.1.9/src/protect/countp.rs:1:\
 12
   |
 1 | use rdll::{SEXP, R_NilValue, Rf_protect, Rf_unprotect};
   |            ^^^^ no `SEXP` in `rdll`

 error[E0432]: unresolved import `rdll::R_NilValue`
  --> /home/elferdo/.cargo/registry/src/github.com-1ecc6299db9ec823/rustr-0.1.9/src/protect/countp.rs:1:\
 18
   |
 1 | use rdll::{SEXP, R_NilValue, Rf_protect, Rf_unprotect};
   |                  ^^^^^^^^^^ no `R_NilValue` in `rdll`
```

followed by other 320 errors.

Some details of my installation:

* FreeBSD 11.0-RELEASE-p2 #0: Mon Oct 24 06:55:27 UTC 2016
* rustc 1.13.0 (in path)
* cargo 0.13.0 (built 2016-12-07) (in path)
* R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"

Any help with this will be greatly appreciated.

Best,
Fernando

**Comment by elferdo** [comment]
Digging a little bit I found `src/rdll/mod.rs` that reads:

```
#[cfg(all(any(target_os="linux",target_os="macos"), target_pointer_width = "64"))]
pub mod unix64;
#[cfg(all(any(target_os="linux",target_os="macos"), target_pointer_width = "64"))]
pub use self::unix64::*;
```
I think chaning that to:
```
#[cfg(all(any(target_os="linux",target_os="macos",target_os="freebsd"), target_pointer_width = "64"))]
pub mod unix64;
#[cfg(all(any(target_os="linux",target_os="macos",target_os="freebsd"), target_pointer_width = "64"))]
pub use self::unix64::*;
```
but I'm not sure how to test it. I will investigate further.

**Comment by qinwf** [comment]
Thanks for the report. I did not test it on freebsd before. This rdll mod is generated by https://github.com/Yamakaky/rust-bindgen, which may be platform related. So I may need to create a freebsd virtualbox, and run code gen on freebsd to make sure that rdll on freebsd are the same as unix64.

**Comment by qinwf** [comment]
I test it on FreeBSD, and it works now. It seems that FreeBSD does not support the original Makevars in rustinr. https://github.com/rustr/rustinr/blob/master/inst/init/Makevars I add a extra make file for FreeBSD. 

The rust-bindgen are the same for the R interface parts, but they are not well tested yet.

I am not familiar with FreeBSD, and there are no CI platform for it as far as I know, or I need to create a jenkins box for it. For now, Win, Mac, Linux are tested with CI.

**Comment by qinwf** [comment]
The latest commit is not on Crates.io yet. You use a local copy of rustr by

```r
rust(code = '',
depend = '
[dependencies]
rustr = {path = "local/rustr"}
')
```

**Comment by elferdo** [comment]
Thank you very much @qinwf for your prompt reply and quick solution, it works! So far I have only tested the first example on the book, but it certainly is a very nice step.

I think FreeBSD is not a tier-1 platform for rust, but it is well maintained and up-to-date from FreeBSD's side. I don't think there should be any major differences from linux or macos except for OS detection.

Keep up the good work!
