### ISSUE TITLE
Support for variadic functions?

### ISSUE THREAD

**Issue by dodomorandi** [rustr/rustinr#5]
I am trying to port some native R functions to Rust. However, some of these have _default parameter values_. Something like

    fn <- function(arg1, arg2=2, arg3=3.4) {
      /* ... */
    }

At to date, Rust is missing _variadic functions_, but maybe it could be possible to support these signatures as well. I was thinking about the possibility of specifying `Option<_>` as parameter type. In this way, it should be possible to check, inside the function, whether your parameter is `None` or `Some(..)`. In case `None` is matched, a _default value_ is used.

It should be possible to add support for `rustrize` to generate this case, isn't it?

**Comment by qinwf-nuan** [comment]
We can also write an wrapper function with default params. Maybe this is easier than codegen.

```r
rust(code = '
// #[rustr_export]
pub fn fib1_rs(x:u64)-> u64{
    if x == 0 { return(0) };
    if x == 1 { return(1) };
    return (fib1_rs(x - 1)) + fib1_rs(x - 2);
}')

fib1_rs_with_default = function(x = 1) {
  return fib1_rs(x)
}
```

**Comment by qinwf** [comment]
We can also write an wrapper function with default params. Maybe this is easier than codegen.

```r
rust(code = '
// #[rustr_export]
pub fn fib1_rs(x:u64)-> u64{
    if x == 0 { return(0) };
    if x == 1 { return(1) };
    return (fib1_rs(x - 1)) + fib1_rs(x - 2);
}')

fib1_rs_with_default = function(x = 1) {
  return fib1_rs(x)
}
```

**Comment by dodomorandi** [comment]
Yes, this is possible without problem. However, if you consider porting many functions, this solution leads to a good amount of wrapper functions. Obviously, this is not a major issue, but can be quite annoying. Are you considering the possibility of supporting this feature in the future?
