### ISSUE TITLE
Does rustinr provide foreign function interface (ffi) or a C transcompiler?

### ISSUE THREAD

**Issue by MaaniBeigy** [rustr/rustinr#8]
Thank you for your interesting package. As a data scientist, R programmer and Rust developer; the integration of Rust and R is very important for me. 

However, there are some points that are not clear to me.  By using `rustinr::rustrize()`, it seems that C/C++ codes are generated. I am not sure how the resulting R package uses Rust functionality? Does it employ rust compiler to make executable files or the codes are transcompiled to C (as it seems in REXPORT.c , wrapper.c, etc)?

Best wishes

**Comment by qinwf** [comment]
Yes, basically

1. R calls C functions
2. In C functions, they call Rust functions

see 

generated R functions https://github.com/rustr/rsegex/blob/master/R/REXPORT.R

generated C functions https://github.com/rustr/rsegex/blob/master/src/REXPORT.c

generated Rust functions https://github.com/rustr/rsegex/blob/master/src/rustlib/src/export.rs
